export const ProjectData = [
    {
        title: "Hyperparameter Optimization Research",
        key: "Hyperparameter_Optimization_Framework_Evaluation_and_Manual",
        image: 'hpoptimization.png',
        description: "Comprehensive hyperparameter optimization research including implementation guides for Keras Tuner, Optuna, and Scikit-Learn. Currently developing 'A Practitioner's Guide to HPO in Optuna' with systematic algorithm selection frameworks and benchmark datasets. Developed during internship at Corning Incorporated.",
        link: "https://github.com/megemann/HPOptimization",
        readme: "https://github.com/megemann/HPOptimization",
        highlight: true,
        date: "07/2024",
        lastUpdate: "Present",
        skills: ["Optuna", "Keras Tuner", "Python", "Algorithm Benchmarking", "Technical Writing", "Hyperparameter Optimization"],
    },
    {
        title: "Personal Portfolio",
        key: "Personal_Portfolio",
        image: 'personalportfolio.png',
        description: "A simple personal portfolio website that displays my projects. This project makes use of React, CSS, Animations, and Github for version control.",
        link: "https://github.com/megemann/megemann.github.io",
        highlight: false,
        date: "05/2024",
        lastUpdate: "05/2024",
        skills: ["React", "CSS", "Animations"],
    },
    {
        title: "The Define Hotline",
        key: "The_Define_Hotline",
        image: 'TheDefineHotline.png',
        description: "'The Define Hot-line' is a fun vocabulary game that uses random words and definitions to test your vocabulary skills. You have a varying amount of time to pair a definition to a word, and the objective is to get the highest streak possible! There are three modes: Easy, Medium, and Hard; each mode gives you respectively 15, 10, and 5 seconds to answer. This project makes use of React Native, React Native Reanimated, as well as a few API's and a collection of other libraries.",
        link: "https://github.com/megemann/TheDefineHotline",
        highlight: false,
        date: "03/2024",
        lastUpdate: "04/2024",
        skills: ["React Native", "Animations", "API's", "Expo"],
    },
    {
        title: "Utrition",
        key: "Utrition",
        image: 'Utrition.png',
        description: "This project was meant to provide a method for students to easily track their calories, protein, and other macro/micro nutrients. The nutrient information is all gathered from UMass's Certified nutrition program, FoodPro1. This project makes use of React, the MaterialUI library, a Java-SpringBoot backend, and MongoDB as a database.",
        link: "https://github.com/megemann/utrition",
        highlight: false,
        date: "01/2024",
        lastUpdate: "01/2024",
        skills: ["React", "MaterialUI", "Java-SpringBoot", "MongoDB"],
    },
    {
        title: "Minute Munch",
        key: "Minute_Munch",
        image: 'MinuteMunch.png',
        description: "Hack Umass 2023 project constructed over the course of 48 hours. This project was a website that simulated creating orders for items in our Umass Dining Halls, and then also had a function of assigning orders to our delivery men, which you could sign up to be in the app. This project made use of: React, CSS, MongoDB, Github for version control, and Java-SpringBoot.",
        link: "https://github.com/Amandinh0/MinuteMunch",
        highlight: false,
        date: "10/2023",
        lastUpdate: "10/2023",
        skills: ["React", "MongoDB", "Java-SpringBoot", "CSS"],
    },
    {
        title: "RMPStats",
        key: "RMPStats",
        image: 'RMPStats.png',
        description: "A comprehensive dashboard that displays statistics and analysis based on data collected from web scraping Rate My Professor reviews. The project involved data cleaning, compiling data into CSV files, and performing extensive data analysis using Pandas and other statistical tools. The frontend was built using Next.js to display various graphs and statistics. Additionally, the project utilized the Hugging Face API for advanced data analysis.",
        link: "https://github.com/megemann/RMPStats",
        highlight: true,
        date: "01/2025",
        lastUpdate: "05/2025",
        skills: ["Web Scraping", "Data Cleaning", "Pandas", "Data Analysis", "Next.js", "Hugging Face API"],
    }, {
        title: "OnePrompted",
        key: "OnePrompted",
        image: 'OnePrompted.png',
        description: "A custom Gen AI model trained to transform vague, ineffective prompts into highly optimized ones using prompt engineering techniques. Built with Vertex AI and Gemini, this project involved data processing from ShareGPT52k, model fine-tuning, and implementation of knowledge distillation and grounding techniques. The model demonstrated an 18% performance improvement in pairwise evaluations against baseline solutions. This project was developed as a capstone for the Google March 2025 Gen AI 5-day Intensive program.",
        link: "https://github.com/megemann/oneprompted",
        highlight: true,
        date: "03/2025",
        lastUpdate: "04/2025",
        skills: ["Vertex AI", "Fine-Tuning", "Prompt Engineering", "Data Processing", "Knowledge Distillation", "Evaluation Metrics", "Generative AI", "Google Cloud"],
    }
    
]